source 'https://github.com/CocoaPods/Specs.git'

target 'RamblerTyphoonUtils_Example' do
  pod "Typhoon"
  pod "OCMock"
  pod "RamblerTyphoonUtils/AssemblyCollector", :path => "../"
end

target 'RamblerTyphoonUtils_Tests' do
  pod "RamblerTyphoonUtils", :path => "../"
end
