source 'https://github.com/CocoaPods/Specs.git'

target 'RamblerTyphoonUtils_Example', :exclusive => true do
  pod "Typhoon"
  pod "RamblerTyphoonUtils/AssemblyCollector", :path => "../"
end

target 'RamblerTyphoonUtils_Tests', :exclusive => true do
  pod "RamblerTyphoonUtils", :path => "../"
end
